package se.kth.iv1350.amazingpos.view;

import se.kth.iv1350.amazingpos.logapi.FileLogger;
import se.kth.iv1350.amazingpos.model.Sale;
import se.kth.iv1350.amazingpos.model.SaleDisplay;

/**
 * Shows the total revenue generated by all sales
 */

public class TotalRevenueView extends SaleDisplay { 
    private double totalRevenue;


    @Override   
    public void notifyObserver(Sale sale){
        addToTotalRevenue(sale.getFinalAmount());
    }

   
    private void addToTotalRevenue(double amount){  
        this.totalRevenue += amount;
        
        String revenue = Double.toString(totalRevenue);

        System.out.println("");
        System.out.println("#### This is not part of the receipt ####");
        System.out.println("#### Will be viewed on it's own GUI ####");
        System.out.println("####Total Revenue from todays sales####");
        System.out.println("Total revenue would be: " + revenue);
        System.out.println("###################################");
        System.out.println("");
      
        System.out.println("--------------Beginning of receipt-------------------"); //Isn't part of addTotalRevenue
                                                                                       //relocated from view to make output clean

    }

    

     @Override
    protected void doShowTotalIncome(double income) throws Exception{
        if(income < 0){
            throw new Exception("Negative revenue!");
        }
        String revenue = Double.toString(income);
    

        System.out.println("");
        System.out.println("#### This is not part of the receipt ####");
        System.out.println("#### Will be viewed on it's own GUI ####");
        System.out.println("####Total Revenue from todays sales####");
        System.out.println("Total revenue would be: " + revenue);
        System.out.println("###################################");
        System.out.println("");
      
        System.out.println("--------------Beginning of receipt-------------------");


    }

   
    @Override
    protected void handleErrors(Exception e){
        FileLogger revenueLogger = new FileLogger("log.txt");
        revenueLogger.log(e.getMessage());
        
    }

}
