package se.kth.iv1350.amazingpos.view;

import se.kth.iv1350.amazingpos.logapi.FileLogger;
import se.kth.iv1350.amazingpos.model.SaleDisplay;



/**
 * Prints the total revenue generated by all sales to a file
 */
public class TotalRevenueFileOutput extends SaleDisplay{

    
    
    FileLogger revenueLogger = new FileLogger("TotalRevenue.txt");

    @Override
    protected void doShowTotalIncome(double income) throws Exception{
        if(income < 0){
            throw new Exception("Negative revenue!");
        }
        String revenue = Double.toString(income);
        revenueLogger.log(revenue);


    }

    @Override
    protected void handleErrors(Exception e){
        revenueLogger.log(e.getMessage());
        
    }

}

