package se.kth.iv1350.amazingpos.view;

import se.kth.iv1350.amazingpos.model.Sale;
import se.kth.iv1350.amazingpos.model.SaleObserver;

/**
 * Shows the total revenue generated by all sales
 */

public class TotalRevenueView implements SaleObserver { 
    private double totalRevenue;


    @Override   
    public void notifyObserver(Sale sale){
        addToTotalRevenue(sale.getFinalAmount());
    }

   
    private void addToTotalRevenue(double amount){  
        this.totalRevenue += amount;
        
        String revenue = Double.toString(totalRevenue);

        System.out.println("");
        System.out.println("#### This is not part of the receipt ####");
        System.out.println("#### Will be viewed on it's own GUI ####");
        System.out.println("####Total Revenue from todays sales####");
        System.out.println("Total revenue would be: " + revenue);
        System.out.println("###################################");
        System.out.println("");
      
        System.out.println("--------------Beginning of receipt-------------------"); //Isn't part of addTotalRevenue
                                                                                       //relocated from view to make output clean

    }

}
